name: Full Stack CI

on:
  push:
    branches:
      - main
      - develop
      - feature/*

  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      NODE_ENV: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            businesslogic/package-lock.json
            website/package-lock.json

      - name: Install Backend Dependencies
        working-directory: ./businesslogic
        run: npm ci

      # TODO: REMOVE THIS:
      # - name: Build Backend
      #   working-directory: ./businesslogic
      #   run: npm run build

      - name: Run Backend Tests
        working-directory: ./businesslogic
        run: npm test

      - name: Install Frontend Dependencies
        working-directory: ./website
        run: npm ci
      
      - name: Install Playwright Browsers
        working-directory: ./website
        run: npx playwright install

      # - name: Run Frontend Tests
      #   working-directory: ./website
      #   run: npm test

      - name: E2E Tests
        working-directory: ./website
        run: npm run test:e2e

      - name: Build Frontend
        working-directory: ./website
        run: npm run build